# Guía 1

Para el desarrollo de la guía 1, convierto todos los pasos desde MatLab a Python, en caso de no estar disponible o no ser necesario lo comento.

Los equivalentes en Python para el desplegue de mensajes y las operaciones matemáticas básicas o algunas que requieren librerías se muestran en la siguiente celda.

In [9]:
# La funcion print es equivalente a disp
print("Hola mundo")

# Las operaciones aritméticas básicas y la asignación de variables funcionan igual:
print(9 + 9)
z = 9+9
# Para llamar a variables lo hacemos por su nombre
# En modo interactivo funciona igual que en MatLab, pero aquí ocupo print para mostrarlo
print(z)

# En cambio para algunas operaciones trigonómetricas, logarítmicas, etc. Se necesita
# el módulo math de la librería estándar

import math

print(math.sin(10))

Hola mundo
18
18
-0.5440211108893698


Python además se puede ocupar para diferentes cálculos como una calculadora, en la siguiente celda se muestran, además ya utilizamos varios comentarios

In [10]:
operacion = (10.3 + 8 * 5 / 3.33)**5
print(operacion)

# Asignamos una operación a una variable y la imprimimos
w = 10 + 20
print(w)

# para saber el signo de un número hay que testear con if
x = 1
print("-" if x < 0 else "+")

5529599.476353067
30
+


Python tienen diversos tipos de datos, tanto primitivos como compuestos, en su librería estándar hay muchos tipos de datos compuestos que ayudan a manipular datos, pero los más utilizados y que probablemente sirvan para esta materia sean:

- Enteros: Números enteros
- Float: Números de punto flotante
- String: Cádenas de texto, incluso de un solo caracter.
- Listas: Tipo de dato compuesto que puede contener cualquier otro tipo de dato.

Además importando desde módulos de la librería estándar hay tipos de datos útiles como decimales.

Podemos saber el tipo de un dato con la función predeterminada `type()`

In [11]:
# Número de punto o coma flotante
f1 = 3.141592 
print(f1)
print(type(f1))

# Número entero
e1 = 50
print(e1)
print(type(e1))

# Una cadena
c1 = "Una cadena de texto"
print(c1)
print(type(c1))

l1 = [f1, e1, c1]

# Aquí usamos un for para imprimir los elementos de la lista
for e in l1:
    print(e)
    print(type(e))

3.141592
<class 'float'>
50
<class 'int'>
Una cadena de texto
<class 'str'>
3.141592
<class 'float'>
50
<class 'int'>
Una cadena de texto
<class 'str'>


Para el formato numérico python representa y acepta números en notación *e* y además brinda mucha flexibilidad para representar o aproximar (con la función `round()`) números flotantes y/o decimales

In [23]:
from decimal import Decimal

pi_decimal = Decimal("3.121592")
print(pi_decimal)

# Al redondear se genera una nueva variable, sea por asignación o en memoria
pi_redondeado = round(pi_decimal, 4)
print(pi_redondeado)

# En cambio al representar un número como cadena se puede hacer formatear com mucha flexibilidad
pi_formateado = f"{pi_decimal:,.4f}"
print(pi_formateado)
pi_alargado = f"{pi_decimal:,.10f}"
print(pi_alargado)

# También aplica para separadores de miles, punto decimal etc.

cien_mil = 100000
cien_mil_formateado_sv = f"{cien_mil:,.2f}"
print(cien_mil_formateado_sv)

# podemos importar pi desde math para ser más precisos acorde a las necesidades
# Por ejemplo con los quince decimales que se piden en varios ejercicios de esta materia.

import math

pi_de_quince_decimales = f"{math.pi:,.15f}"
print(pi_de_quince_decimales)

# Y observamos la notación E
print(2.5E3)

3.121592
3.1216
3.1216
3.1215920000
100,000.00
3.141592653589793
2500.0


A diferencia de Matlab, Python usa funciones y algunos módulos para operaciones y datos que se ocuparán en esta materia. Además vamos a ocupar una poderosa herramienta de python que puede generar listas muy complejas: Listas por comprensión.

In [19]:
# La función range genera una lista desde cero hasta el número proporcionado menos uno
l2 = range(5)
print([n for n in l2])

# Cuando se brindan 2 argumento el primero es el número inicial y el segundo menos uno el final
l3 = range(4, 10)
print([n for n in l3])

# Un tercer argumento puede servirnos para los pasos entre cada elemento de la lista generada
tabla_de_tres = range(3, 31, 3)
print([n for n in tabla_de_tres])

[0, 1, 2, 3, 4]
[4, 5, 6, 7, 8, 9]
[3, 6, 9, 12, 15, 18, 21, 24, 27, 30]


Las matrices son el tipo de dato que diferencia a Matlab, en Python podemos hacer uso de numpy y las array que parecen ser equivalentes, en cualquier caso mi enfoque será tratar de utilizar el tipo de dato que más convenga en cada operación.

Numpy tiene muchas funcion para la manipulación, creación y operación de matrices.

In [24]:
from numpy import array, random

array_1 = array([1, 2, 3])
array_2 = ([3, 4, 5])

producto_escalar = array_1 @ array_2 # Calculamos el punto escalar de las matrices

print(array_1)
print(array_2)
print(producto_escalar)

# Numpy puede generar matrices aleatorias

# Esta es una matriz con el mínimo en 0, máximo 9, de 3x3 
# Predeterminadamente se utilizan enteros positivos
mi_matriz_aleatoria = random.randint(low=0, high=9, size=(3,3))
print(mi_matriz_aleatoria)


[1 2 3]
[3, 4, 5]
26
[[7 5 4]
 [6 1 3]
 [7 7 1]]
