2. Elaborar un programa que lea una matriz de números (de cualquier dimensión) y muestre los siguiente elementos:

-Suma de los elementos de cada una de sus filas
-Suma de los elementos de cada una de sus columnas
-Adicionalmente, si la matriz es cuadrada, deberá mostrarse la suma de elementos de la diagonal principal.

Para el desarrollo de este ejercicio vamos a utilizar la clase ndarray (Arreglo de Numpay) que es la recomendada para operaciones con matrices dentro de Numpay.

In [3]:
import numpy as np

#ejemplo:

matriz_1 = np.array([[2,3,-5],[7,0,9],[-2,-5,5]])
print(matriz_1)

# Dado que las array se pueden recorrer con bucles, haremos una función independiente
# para cada aplicativo y luego las unimos

def sumar_filas_de_matriz(matriz: np.array)->list:
    """
    Dada una matriz subclase de np.array, retorna una list en la cual cada elemento
    es la suma de cada fila de la matriz
    """
    if not isinstance(matriz, np.ndarray):
        raise TypeError("El argumento no es una ndarray de Numpy")
    # Al iterar se hace predeterminadamente por filas
    resultado = []
    for fila in matriz:
        suma = 0
        for elemento in fila:
            suma += elemento
        resultado.append(suma)
    return(resultado)

print(sumar_filas_de_matriz(matriz_1))


def sumar_columnas_de_matriz(matriz: np.array)->list:
    """
    Dada una matriz subclase de np.array, retorna una list en la cual cada elemento
    es la suma de cada columan de la matriz. 
    Para intercambiar columnas por filas, simplemente transponemos la matriz y llamamos 
    a la función de sumar filas
    """
    return sumar_filas_de_matriz(matriz.T)

print(sumar_columnas_de_matriz(matriz_1))

def sumar_diagonal_de_matriz_cuadrada(matriz: np.array)->list:
    """
    Dada una matriz subclase de np.array, si esta es cuadrada, retorna
    la suma de los elementos de la diagonal, si no retorna la lista vacía.
    Primero verificamos la clase del argumento, luego si esta es de 2
    dimensiones y finalmente si el número de columnas es igual al de filas
    """
    if not isinstance(matriz, np.ndarray):
        raise TypeError("El argumento no es una ndarray de Numpy")
    if len(matriz.shape) != 2:
        raise ValueError("El array suministrado debe ser una matriz bidimensional")
    if matriz.shape[0] != matriz.shape[1]:
        raise ValueError("La matriz suministrada debe ser cuadrada.")
    # iteramos para que vaya con el mismo número
    total = 0
    iterador = 0
    for fila in matriz:
        total += fila[iterador]
        iterador += 1
    return total

print(sumar_diagonal_de_matriz_cuadrada(matriz_1))


# Ahora hacemos una función para tabular todos los resultados

def ejercicio_2(matriz: np.array)->None:
    """
    Imprimimos en pantalla todo lo obtenido de las funciones anteriores según el ejercicio
    """

    sumas_de_filas = sumar_filas_de_matriz(matriz)
    n = 1
    for resultado in sumas_de_filas:
        print(f"Suma de elementos de la fila {n}: {resultado}")
        n += 1
    sumas_de_columnas = sumar_columnas_de_matriz(matriz)
    n = 1
    for resultado in sumas_de_columnas:
        print(f"Suma de elementos de la columna {n}: {resultado}")
        n += 1
    
    try:
        suma_de_diagonal = sumar_diagonal_de_matriz_cuadrada(matriz)
        print(f"Suma de elementos de la diagonal principal: {suma_de_diagonal}")
    except:
        print("La matriz no es cuadrada.")

ejercicio_2(matriz_1)


[[ 2  3 -5]
 [ 7  0  9]
 [-2 -5  5]]
[0, 16, -2]
[7, -2, 9]
7
Suma de elementos de la fila 1: 0
Suma de elementos de la fila 2: 16
Suma de elementos de la fila 3: -2
Suma de elementos de la columna 1: 7
Suma de elementos de la columna 2: -2
Suma de elementos de la columna 3: 9
Suma de elementos de la diagonal principal: 7
